application: wed-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /tab_content
  static_dir: templates/tab_content

- url: .*
  script: wed_app.app

libraries:
- name: webapp2
  version: latest

- name: jinja2                                                                  
  version: latest  
